[package]
name = "employer_agreement"
version = "25.04.26"
edition = "2025.3"
description = "Employer registration and worker identity mapping contract for the PNW-MVP system."
authors = "PNW Dev Team"
license = "Proprietary"
main = "src/main.leo"  # <-- must match real file location

[program]
path = "src/main.leo"  # <-- optional but cleaner
