[package]
name = "employer_agreement"
version = "25.04.09"
edition = "2025.3"
description = "Employer registration and worker identity mapping contract for the PNW-MVP system."
authors = "PNW Engineering Team"
license = "Proprietary"
main = "src/main.leo"
