[package]
name = "employer_agreement"
version = "25.03.25"
edition = "2025.3"
main = "main.leo"  # Relative path, not absolute

[dependencies]
subdao_reserve = { path = "../subdao_reserve" }
weekly_payroll_pool = { path = "../weekly_payroll_pool" }
oversightdao_reserve = { path = "../oversightdao_reserve" }
process_tax_compliance = { path = "../process_tax_compliance" }
