[package]
name = "pnw_mvp"
version = "3.13.25"
edition = "2025"

[dependencies]
credits = { path = "./src/credits/main.leo" }
employer_agreement = { path = "./src/employer_agreement/main.leo" }
process_tax_compliance = { path = "./src/process_tax_compliance/main.leo" }
subdao_reserve = { path = "./src/subdao_reserve/main.leo" }
oversightdao_reserve = { path = "./src/oversightdao_reserve/main.leo" }
pncw_payroll = { path = "./src/pncw_payroll/main.leo" }
pniw_payroll = { path = "./src/pniw_payroll/main.leo" }
weekly_payroll_pool = { path = "./src/weekly_payroll_pool/main.leo" }
