[package]
name = "pnw_mvp"
version = "1.1.1"
edition = "2023"

[dependencies]
credits = { path = "./src/credits.leo" }
employer_agreement = { path = "./src/employer_agreement.leo" }
process_tax_compliance = { path = "./src/process_tax_compliance.leo" }
subdao_reserve = { path = "./src/subdao_reserve.leo" }
oversightdao_reserve = { path = "./src/oversightdao_reserve.leo" }
pncw_payroll = { path = "./src/pncw_payroll.leo" }
pniw_payroll = { path = "./src/pniw_payroll.leo" }
weekly_payroll_pool = { path = "./src/weekly_payroll_pool.leo" }
