[package]
name = "process_tax_compliance"
version = "25.04.26"
edition = "2025.3"
license = "Proprietary"
authors = "PNW Dev Team"
description = "Handles employer tax compliance logic for the PNW MVP"
main = "src/main.leo"

[program]
path = "src/main.leo"

[dependencies]
pncw_payroll = { path = "../pncw_payroll" }
pniw_payroll = { path = "../pniw_payroll" }
subdao_reserve = { path = "../subdao_reserve" }
employer_agreement = { path = "../employer_agreement" }
