[package]
name = "process_tax_compliance"
version = "25.03.13"
edition = "2025.3"
main = "src/process_tax_compliance/main.leo"   # Explicitly set the main entry file

[dependencies]
credits = { path = "../credits" }
pncw_payroll = { path = "../pncw_payroll" }
pniw_payroll = { path = "../pniw_payroll" }
subdao_reserve = { path = "../subdao_reserve" }
worker_profiles = { path = "../worker_profiles" }
