[package]
name = "subdao_reserve"
version = "25.04.09"
edition = "2025.3"
license = "Proprietary"
description = "Handles reserve logic for each subDAO, including funding payroll and managing tax obligations"
authors = "PNWBNW Dev Team"

[dependencies]
weekly_payroll_pool = { path = "../weekly_payroll_pool" }
process_tax_compliance = { path = "../process_tax_compliance" }

[leo]
network = "testnet"
