[package]
name = "subdao_reserve"
version = "25.04.26"
edition = "2025.3"
license = "Proprietary"
description = "Handles reserve logic for each subDAO, including funding payroll and managing tax obligations"
authors = "PNW Dev Team"
main = "src/main.leo"

[program]
path = "src/main.leo"

[dependencies]
weekly_payroll_pool = { path = "../weekly_payroll_pool" }
process_tax_compliance = { path = "../process_tax_compliance" }
