[package]
name = "plonky2_prover"
version = "0.1.0"
edition = "2021"

[dependencies]
plonky2 = "0.1.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
anyhow = "1.0"

[profile.release]
opt-level = "z"     # Optimize for size (optional)
lto = true          # Link-time optimization (smaller binaries)
codegen-units = 1   # Single-threaded for smaller output

[[bin]]
name = "hash_worker"
path = "cli/hash_worker.rs"

[[bin]]
name = "verify_proof"
path = "cli/verify_proof.rs"
