[package]
name = "weekly_payroll_pool"
version = "25.3.14"
edition = "2025.3"

[dependencies]
credits = { path = "../credits" }
employer_agreement = { path = "../employer_agreement" }
process_tax_compliance = { path = "../process_tax_compliance" }
subdao_reserve = { path = "../subdao_reserve" }
pncw_payroll = { path = "../pncw_payroll" }
pniw_payroll = { path = "../pniw_payroll" }
