[package]
name = "weekly_payroll_pool"
version = "25.04.09"
edition = "2025.3"
authors = ["PNW MVP Team"]
description = "Handles weekly payroll disbursements from SubDAO reserves to workers via PNCW and PNIW channels."
license = "PNW-MVP Proprietary License"
main = "main.leo"

[dependencies]
credits = { path = "../credits" }
subdao_reserve = { path = "../subdao_reserve" }
pncw_payroll = { path = "../pncw_payroll" }
pniw_payroll = { path = "../pniw_payroll" }

[leo]
network = "testnet"
