[package]
name = "credential_nft"
version = "0.1.0"
description = "Soulbound credential NFT system for worker certifications"
edition = "2023"

[program]
name = "credential_nft.aleo"

[dependencies]
aleo_std = { tag = "v2.0.0", registry = "https://github.com/ProvableHQ/aleo-std" }

[build]
entry = "src/main.leo"
output = "program.json"

[settings]
# Optional future hooks
default_owner = "aleo1oversightdao000000000000000000000000000000000000000000000000000"
