[package]
name = "oversightdao_reserve"
version = "25.04.26"
edition = "2025.3"
description = "Manages the reserve funds for OversightDAO for payroll compliance and withdrawals"
license = "Proprietary"
authors = "PNW Dev Team"
main = "src/main.leo"

[program]
path = "src/main.leo"
