[package]
name = "worker_profiles"
version = "25.04.22"
edition = "2025.3"
license = "Proprietary"
description = "Shared worker mapping definitions and constants used across PNW-MVP contracts."
authors = "PNWBNW Dev Team"

[dependencies]

[leo]
network = "testnet"
