[package]
name = "worker_profiles"
version = "25.04.26"
edition = "2025.3"
description = "Manages worker profiles and credentials"
license = "Proprietary"
authors = "PNW Dev Team"
main = "src/main.leo"

[program]
path = "src/main.leo"
