[package]
name = "employer_registry"
version = "25.05.28"
edition = "2025.3"
description = "Employer registration and identity contract for the PNW-MVP system."
authors = "PNW Dev Team"
license = "Proprietary"
main = "src/main.leo"

[program]
path = "src/main.leo"
