name: Deploy PNW-MVP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout repository
        uses: actions/checkout@v3

      - name: 🔑 Set Aleo private key from repository secret
        run: echo "ALEO_PRIVATE_KEY=${{ secrets.ALEO_PRIVATE_KEY }}" >> $GITHUB_ENV

      - name: 🛠️ Install Leo CLI from provided zip
        run: |
          curl -L -o leo.zip https://github.com/PNWBNW/pnw_mvp/releases/download/leo-2.4.1/leo-2.4.1.zip
          unzip leo-2.4.1.zip -d $HOME/.aleo
          chmod +x $HOME/.aleo/leo
          echo "$HOME/.aleo" >> $GITHUB_PATH

      - name: ✅ Verify Leo Installation
        run: |
          leo --version

      - name: 🔧 Set permissions for deployment script
        run: chmod +x deploy_pnw_mvp.sh

      - name: 🚀 Deploy contracts using script
        run: ./deploy_pnw_mvp.sh
