name: Deploy to Aleo Testnet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip curl jq

      - name: Download and Setup Leo CLI
        run: |
          curl -L -o leo.zip https://github.com/PNWBNW/pnw_mvp/releases/download/leo-2.4.1/leo-mainnet-x86_64-unknown-linux-gnu.zip
          unzip leo.zip
          sudo mv leo /usr/local/bin/leo
          sudo chmod +x /usr/local/bin/leo
          leo --version

      - name: Clean and Build PNW_MVP Project
        run: |
          leo clean
          leo build --network testnet

      - name: Deploy to Aleo Testnet
        env:
          ALEO_PRIVATE_KEY: ${{ secrets.ALEO_PRIVATE_KEY }}
        run: |
          PROGRAM_NAME=$(jq -r '.program' program.json)
          if [ -z "$PROGRAM_NAME" ]; then
            echo "Error: 'program' not defined in program.json"
            exit 1
          fi
          echo "Deploying $PROGRAM_NAME..."
          leo deploy "$PROGRAM_NAME" --private-key="$ALEO_PRIVATE_KEY" --network testnet || {
            echo "Deployment of $PROGRAM_NAME failed."
            exit 1
          }
